name: Nexia
description: "A new Flutter project."

publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+15

platforms:
  android:
  ios:
  web:
  linux:
  windows:
  macos:

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.2.1
  mellowtel: ^0.0.4
  http: ^1.0.0
  path_provider: ^2.1.3
  permission_handler: ^10.3.6
  provider: ^6.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  mime: ^1.0.5
  dio: ^5.4.3+1
  fl_chart: ^0.68.0
  flutter_colorpicker: ^1.0.0
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^5.2.0
  image_picker: ^1.1.2
  dash_chat_2: ^0.0.20
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0
  chat_bubbles: ^1.6.0
  flutter_sound:
    path: packages/flutter_sound
  # waveform: ^0.0.1-nightly.49
  flutter_svg: ^2.0.9
  flutter_launcher_icons: ^0.13.1
  lottie: ^3.0.0
  animated_splash_screen: ^1.3.0
  flutter_lints: ^4.0.0
  rive: ^0.12.0 
  flutter_animate: ^4.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  loggy: ^2.0.3
  go_router: ^11.1.3
  cached_network_image: ^3.3.0
  hive: ^2.2.3
  flutter_chat_ui: ^1.6.12
  uuid: ^4.3.3
  flutter_chat_types: ^3.6.2
  flutter_secure_storage: ^8.0.0
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  file_picker: ^6.1.1
  pdf_gemini: ^0.0.3
  syncfusion_flutter_pdf: 
  google_generative_ai:
  google_gemini:
  flutter_gemini:
  google_fonts:
  syncfusion_flutter_pdfviewer:
  flutter_markdown:
  sizer: ^3.0.4
  shared_preferences: ^2.2.2
  intl:
  url_launcher:
  flutter_spinkit: ^5.1.0  
  firebase_core: ^3.1.0
  firebase_auth: ^5.0.0
  firebase_database: ^11.3.2
  firebase_storage: ^12.4.2
  cloud_firestore: ^5.6.3
  dropdown_search: ^5.0.0
  
  material_design_icons_flutter: ^5.0.0
  vector_math: ^2.1.1
  custom_radio_grouped_button: ^2.2.1
  flutter_material_color_picker: ^1.0.0

flutter_icons:
  image_path: "assets/app_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/s1.png
    - assets/s2.png
    - assets/robocat.riv
    - assets/fonts/
    - assets/images/
    - assets/animations/
    - Sets/E3.txt
    - Sets/E6.txt
    - Sets/E12.txt
    - Sets/E24.txt
    - Sets/E48.txt
    - Sets/E96.txt
    - Sets/E192.txt
    - images/0.png

  # Optional: Customize fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
