// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaZi5DAA0m849403WgHFyoDt_x02jOFR8',
    appId: '1:1063750040298:web:f6e93b86fd2789ffe1f593',
    messagingSenderId: '1063750040298',
    projectId: 'nexia-notes-799b5',
    authDomain: 'nexia-notes-799b5.firebaseapp.com',
    storageBucket: 'nexia-notes-799b5.firebasestorage.app',
    measurementId: 'G-H1RQJEDTBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsMJtH5x64tISoWwkdVS34DVol_hBTmDI',
    appId: '1:1063750040298:android:a205f1c1a1984ffce1f593',
    messagingSenderId: '1063750040298',
    projectId: 'nexia-notes-799b5',
    storageBucket: 'nexia-notes-799b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYHuMulsCXP_BWAyH7HJTlcjRP4xNyLbA',
    appId: '1:1063750040298:ios:845806e9cf78e0dce1f593',
    messagingSenderId: '1063750040298',
    projectId: 'nexia-notes-799b5',
    storageBucket: 'nexia-notes-799b5.firebasestorage.app',
    iosBundleId: 'vishnumeta.nexia.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYHuMulsCXP_BWAyH7HJTlcjRP4xNyLbA',
    appId: '1:1063750040298:ios:21e56dcc161fc26ae1f593',
    messagingSenderId: '1063750040298',
    projectId: 'nexia-notes-799b5',
    storageBucket: 'nexia-notes-799b5.firebasestorage.app',
    iosBundleId: 'com.vishnumeta.flutterApplication2',
  );
}
