name: flutter_sound
description: "A Flutter plugin for audio recording, playback, and more."
version: 8.5.0
homepage: https://github.com/Dooboolab/flutter_sound
environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# ...other dependencies and configurations...